### ISSUE TITLE
allow object oriented usage

### ISSUE THREAD

**Issue by jquense** [fabiospampinato/khroma#31]
:wave: hey there I'm working on a Sass like preprocessor and was hoping to use Khroma for color logic. The issue tho is that i really need to be able to create reusable Color objects to e.g. store as the values of a variable declaration. THe problem here is that Khroma reuses the same Channels instance for all work so it doesn't seem possible to store an intermediate representation of the color channels since any other color will mutate the same data. I see why this is the case, but any chance of getting a version of the API that allows creating reusable `Color` instances from strings?

**Comment by fabiospampinato** [comment]
Sure, I could add a way to output non-reused `Channels` instances, although this is a bit of an implementation detail and I'd prefer not to expose it if possible, why do you _need_ this? Is this purely for performance reasons?

**Comment by fabiospampinato** [comment]
Maybe a nice quick way to fix this would be to add a "clone" method to the "Channels" class. However you could potentially already clone Channel classes already manually.
