### ISSUE TITLE
License reported as unknown

### ISSUE THREAD

**Issue by eta-orionis** [fabiospampinato/khroma#35]
The license is not specified in the package.json file, therefore the package is listed as UNLICENSED (License=none) on the npm registry.

This makes the legal situation unclear and results in build failures due to unknown license constraints.

**Comment by fabiospampinato** [comment]
Thanks but it's on purpose, if you are relying on the `license` field of of `package.json` to understand the license of the packages you are using you are doing it in a brittle/broken way. Read [this](https://github.com/fabiospampinato/khroma/pull/34#issuecomment-1506724778) and [this](https://github.com/fabiospampinato/khroma/pull/33#issuecomment-1321250887).
