### ISSUE TITLE
License missing in package

### ISSUE THREAD

**Issue by LunaticMuch** [fabiospampinato/khroma#37]
The current `package.json` file does not include the `license` attribute. This is an issue for those systems which mirror or proxy access the download of external packages from npmjs.com.
Between version 2.0.0 and 2.1.0, the file `LICENSE` was renamed in `license`. This is fine, although not the most common practice, and it is not captured by some of those system which actively look for a `LICENSE` file and the license attribute in the `package.json`. The license shown on GitHub is not captured within the package, so it's not relevant when a package is downloaded.

Thus, the `package.json` should correctly include the `license` attribute and a new version of the package should be built.

**Comment by fabiospampinato** [comment]
Read this https://github.com/fabiospampinato/khroma/issues/35

It looks like the systems you are referring to need a little upgrade.
