### ISSUE TITLE
Double entry for dimgrey color keyword

### ISSUE THREAD

**Issue by alogical** [fabiospampinato/khroma#40]
[keyword.ts #line 56-57](https://github.com/fabiospampinato/khroma/blob/4968165afb0d3d09be66497e7985a34f7bfe6d42/src/color/keyword.ts#L56-57)

The below line is repeated twice.
```
dimgray: '#696969',
```

**Comment by alogical** [comment]
[keyword.ts #line 92-93]( https://github.com/fabiospampinato/khroma/blob/4968165afb0d3d09be66497e7985a34f7bfe6d42/src/color/keyword.ts#L92)

Keyword repeated twice
```
lightslategray: '#778899',
```

**Comment by alogical** [comment]
Sorry for wasting your time. I see it now. It's grey and gray. One with spelled with an 'e' and the other with an 'a'.

**Comment by fabiospampinato** [comment]
Yeah it's kinda funny that they added both of them to whatever color standard everybody copied this color map from 🤣
